---
title: "Natividad dataset analysis"
author: "Reilly"
date: "11/30/2018"
output: html_document
---

#```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
#```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)


# Side note----

pkgs = c("tidyverse", "plotly" , "lubridate")

loadPackages = function(pkgs){

  temp.packages = function(a){
      if(!require(a, character.only = TRUE)){
        install.packages(a)
        library(a, character.only = TRUE)
      }
    }

  lapply(pkgs, load.packages)

}


sapply(list.files(pattern="[.]R$", path="./Functions", full.names=TRUE), source)


```

## Read in the Natividad data
 Using the recent dataset that was supposedly cleaned by Brock (from Guilio)
 File originally called: natividad_temp_do_2013_2018.csv

```{r}
natividad_temp <- read_csv("~/Documents/Courses/MERP2/SafeSpacesData/natividad_temp_do_2013_2018.csv")
```

Now let's check and see what what we've got:
```{r}
summary(natividad_temp)

head(natividad_temp)
```

